name: CI

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    environment: Foundry_Test
    permissions:
      contents: read
    env:
      SPENDING_PRIVATE_KEYS: ${{ secrets.SPENDING_PRIVATE_KEYS }}
      SPENDING_PUBLIC_KEYS: ${{ secrets.SPENDING_PUBLIC_KEYS }}
      VIEWING_PRIVATE_KEYS: ${{ secrets.VIEWING_PRIVATE_KEYS }}
      VIEWING_PUBLIC_KEYS: ${{ secrets.VIEWING_PUBLIC_KEYS }}
      PAYMASTER_OWNER: ${{ secrets.PAYMASTER_OWNER }}
      PAYMASTER_MANAGER: ${{ secrets.PAYMASTER_MANAGER }}
      PAYMASTER_SIGNER: ${{ secrets.PAYMASTER_SIGNER }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv
